services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: lingua_lair
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - linguadb:/var/lib/postgresql/data

volumes:
  linguadb:
